import { GoogleGenAI } from '@google/genai';

export interface NegotiationResult {
  present_argument: string;
  future_argument: string;
  resolution: string;
  outcome: 'proceed' | 'skip' | 'reduced';
}

/**
 * Call Site #2: The Negotiation Debate
 * Receives ONLY real numbers generated by the engine. Never invents data.
 */
export async function runNegotiation(
  apiKey: string,
  merchant: string,
  amount: number,
  category: string,
  baselineSafe: number,
  scenarioSafe: number,
  baselineRisk: string,
  scenarioRisk: string
): Promise<NegotiationResult> {
  if (!apiKey) {
    throw new Error('No API key provided.');
  }

  const ai = new GoogleGenAI({ apiKey });

  const payload = `
    User wants to buy: ${merchant} for ₹${amount} in ${category}.
    Real engine data:
    - Safe to spend drops from ₹${baselineSafe} to ₹${scenarioSafe}.
    - Risk status goes from ${baselineRisk} to ${scenarioRisk}.
  `;

  // We ask Gemini to simulate both personas in one structured shot to save latency,
  // honoring the exact system instructions from the master brief.
  const prompt = `
    You are the FINVERSE Negotiation Engine. You will simulate two agents debating a purchase.
    
    Here is the real financial data (DO NOT INVENT ANY OTHER NUMBERS):
    ${payload}

    Agent 1: "Present You"
    You are "Present You" — the user's voice of immediate desire, arguing FOR a purchase. You will receive real calculated financial numbers. Use ONLY these numbers, never invent one. Make a genuine, human case for the purchase in one paragraph, first person, under 40 words, conversational, no hedging.

    Agent 2: "Future You"
    You are "Future You" — grounded and protective. You will receive the same real numbers plus Present You's argument. Counter using specific real figures only (ending balance difference, goal-delay days, risk change) — never a vague warning. One paragraph, first person, under 40 words, calm not scolding. End with a concrete resolution: "buy it, but skip X" / "wait N days" / "you're clear."

    Output a valid JSON object strictly matching this schema, without markdown formatting:
    {
      "present_argument": "...",
      "future_argument": "...",
      "resolution": "...",
      "outcome": "proceed" | "skip" | "reduced"
    }
  `;

  const response = await ai.models.generateContent({
    model: 'gemini-2.5-flash',
    contents: prompt
  });

  let responseText = response.text || '';
  responseText = responseText.replace(/```json/g, '').replace(/```/g, '').trim();
  
  try {
    const parsed = JSON.parse(responseText);
    return parsed as NegotiationResult;
  } catch (e) {
    console.error("Gemini parse error", responseText);
    throw new Error("Failed to parse Gemini response.");
  }
}
